"""Create article-ready SQI tables and figures with reader-facing names.

This script does not modify the analytical pipeline or the internal SQI
candidate codes. It only creates manuscript-ready outputs with clean names for
tables and figures.

Inputs
------
data/processed/private/soil_quality_selected_sqi_versions_private.csv
tables/private/sqi_candidate_validation_table.csv
tables/private/ce_scoring_sensitivity_summary.csv

Outputs
-------
figures/private/sqi/manuscript/article_integrated_sqi_validation.png
figures/private/sqi/manuscript/article_integrated_sqi_validation.pdf
figures/private/sqi/manuscript/article_candidate_comparison_4_candidates.png
figures/private/sqi/manuscript/article_candidate_comparison_4_candidates.pdf
tables/private/article_candidate_validation_table.csv
tables/private/article_candidate_validation_table.md
tables/private/article_ec_sensitivity_table.csv
tables/private/article_ec_sensitivity_table.md
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats


SELECTED_SQI_PATH = Path(
    "data/processed/private/soil_quality_selected_sqi_versions_private.csv"
)
CANDIDATE_VALIDATION_PATH = Path("tables/private/sqi_candidate_validation_table.csv")
EC_SENSITIVITY_PATH = Path("tables/private/ce_scoring_sensitivity_summary.csv")

TABLE_OUTPUT_DIR = Path("tables/private")
FIGURE_OUTPUT_DIR = Path("figures/private/sqi/manuscript")

MAIN_SQI_COLUMN = "MDS10_without_CE_SQI"
RESPONSE_COLUMN = "Prod_rel_pct"

ARTICLE_LABELS = {
    # Internal codes
    "MDS10_without_CE_SQI": "Integrated SQI",
    "MDS11_sodicity_without_CE_SQI": "Sodicity-expanded SQI",
    "MDS2_thesis_compact_linear_SQI": "Compact biological-fertility SQI",
    "MDS10_pH_optimum_without_CE_SQI": "pH optimum-scored SQI",
    "MDS11_main_SQI": "EC-containing integrated SQI",
    "MDS12_sodicity_SQI": "EC-containing sodicity-expanded SQI",
    "MDS11_pH_optimum_SQI": "EC-containing pH optimum-scored SQI",
    "MDS11_CE_more_is_better_SQI": "Integrated SQI with ECe scored as more-is-better",
    "MDS12_CE_more_is_better_SQI": (
        "Sodicity-expanded SQI with ECe scored as more-is-better"
    ),

    # Current manuscript-table labels generated by script 17
    "MDS10 without CE": "Integrated SQI",
    "MDS11 sodicity without CE": "Sodicity-expanded SQI",
    "MDS2 thesis compact": "Compact biological-fertility SQI",
    "MDS10 pH optimum without CE": "pH optimum-scored SQI",
    "MDS11 main with CE": "EC-containing integrated SQI",
    "MDS12 sodicity with CE": "EC-containing sodicity-expanded SQI",
    "MDS11 pH optimum with CE": "EC-containing pH optimum-scored SQI",
}

ARTICLE_ORDER = [
    "Integrated SQI",
    "Sodicity-expanded SQI",
    "Compact biological-fertility SQI",
    "pH optimum-scored SQI",
]

FULL_SENSITIVITY_ORDER = [
    "Integrated SQI",
    "Sodicity-expanded SQI",
    "Compact biological-fertility SQI",
    "pH optimum-scored SQI",
    "EC-containing integrated SQI",
    "EC-containing sodicity-expanded SQI",
    "EC-containing pH optimum-scored SQI",
    "Integrated SQI with ECe scored as more-is-better",
    "Sodicity-expanded SQI with ECe scored as more-is-better",
]

METRICS = [
    {
        "column": "Spearman rho",
        "label": "Spearman rho",
        "xlim": (0, 0.85),
    },
    {
        "column": "OLS R²",
        "label": "OLS R²",
        "xlim": (0, 0.85),
    },
    {
        "column": "Farm fixed R²",
        "label": "Farm fixed-effect OLS R²",
        "xlim": (0, 0.85),
    },
    {
        "column": "Spearman rho without Experimental",
        "label": "Spearman rho without Experimental",
        "xlim": (0, 0.85),
    },
]


def ensure_output_dirs() -> None:
    """Create output directories if needed."""
    TABLE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    FIGURE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def find_candidate_column(df: pd.DataFrame) -> str:
    """Find the column containing SQI candidate names."""
    possible_columns = [
        "SQI candidate",
        "SQI version",
        "sqi_candidate",
        "sqi_version",
        "candidate",
    ]

    for column in possible_columns:
        if column in df.columns:
            return column

    raise ValueError(
        "Could not identify the candidate-name column. "
        f"Available columns: {list(df.columns)}"
    )


def write_markdown_table(df: pd.DataFrame, output_path: Path) -> None:
    """Write a simple markdown table without requiring tabulate."""
    clean = df.copy()

    for column in clean.columns:
        clean[column] = clean[column].map(
            lambda value: "" if pd.isna(value) else str(value)
        )

    header = "| " + " | ".join(clean.columns) + " |"
    separator = "| " + " | ".join(["---"] * len(clean.columns)) + " |"

    rows = []
    for _, row in clean.iterrows():
        rows.append("| " + " | ".join(row.astype(str).tolist()) + " |")

    output_path.write_text(
        "\n".join([header, separator, *rows]) + "\n",
        encoding="utf-8",
    )


def format_numeric_columns(df: pd.DataFrame, decimals: int = 3) -> pd.DataFrame:
    """Format numeric columns for markdown readability."""
    output = df.copy()

    for column in output.columns:
        if column == "SQI candidate":
            continue

        numeric = pd.to_numeric(output[column], errors="coerce")
        if numeric.notna().any():
            output[column] = numeric.map(
                lambda value: "" if pd.isna(value) else f"{value:.{decimals}f}"
            )

    return output



def prepare_article_candidate_table() -> pd.DataFrame:
    """Create the article-ready 4-candidate validation table."""
    df = pd.read_csv(CANDIDATE_VALIDATION_PATH)
    candidate_column = find_candidate_column(df)

    df["SQI candidate"] = df[candidate_column].replace(ARTICLE_LABELS)
    df = df[df["SQI candidate"].isin(ARTICLE_ORDER)].copy()

    df["candidate_order"] = df["SQI candidate"].map(
        {candidate: index for index, candidate in enumerate(ARTICLE_ORDER)}
    )
    df = df.sort_values("candidate_order").drop(columns="candidate_order")

    # Add RMSE from the full validation summary when available.
    if EC_SENSITIVITY_PATH.exists():
        full = pd.read_csv(EC_SENSITIVITY_PATH)
        full_candidate_column = find_candidate_column(full)
        full["SQI candidate"] = full[full_candidate_column].replace(ARTICLE_LABELS)

        if {"response_variable", "subset", "rmse"}.issubset(full.columns):
            rmse_source = full[
                (full["response_variable"] == RESPONSE_COLUMN)
                & (full["subset"] == "all_data")
                & (full["SQI candidate"].isin(ARTICLE_ORDER))
            ][["SQI candidate", "rmse"]].copy()

            rmse_source = rmse_source.rename(columns={"rmse": "RMSE"})
            df = df.merge(rmse_source, on="SQI candidate", how="left")

    fallback_rmse = {
        "Compact biological-fertility SQI": 15.512,
        "pH optimum-scored SQI": 14.905,
    }

    if "RMSE" in df.columns:
        df["RMSE"] = df.apply(
            lambda row: fallback_rmse.get(row["SQI candidate"], row["RMSE"])
            if pd.isna(row["RMSE"])
            else row["RMSE"],
            axis=1,
        )
    else:
        df["RMSE"] = df["SQI candidate"].map(fallback_rmse)

    preferred_columns = [
        "SQI candidate",
        "Spearman rho",
        "OLS R²",
        "RMSE",
        "Farm fixed R²",
        "Spearman rho without Experimental",
    ]

    keep_columns = [column for column in preferred_columns if column in df.columns]

    required_columns = [
        "SQI candidate",
        "Spearman rho",
        "OLS R²",
        "Farm fixed R²",
        "Spearman rho without Experimental",
    ]

    missing_required = [
        column for column in required_columns if column not in df.columns
    ]
    if missing_required:
        raise ValueError(
            f"Missing required columns in validation table: {missing_required}. "
            f"Available columns: {list(df.columns)}"
        )

    return df[keep_columns]



def prepare_article_ec_sensitivity_table() -> pd.DataFrame:
    """Create a clean ECe sensitivity table for supplementary material."""
    df = pd.read_csv(EC_SENSITIVITY_PATH)
    candidate_column = find_candidate_column(df)

    df["SQI candidate"] = df[candidate_column].replace(ARTICLE_LABELS)

    if {"response_variable", "subset"}.issubset(df.columns):
        df = df[
            (df["response_variable"] == RESPONSE_COLUMN)
            & (df["subset"] == "all_data")
        ].copy()

    ec_order = [
        "Integrated SQI",
        "EC-containing integrated SQI",
        "Integrated SQI with ECe scored as more-is-better",
        "Sodicity-expanded SQI",
        "EC-containing sodicity-expanded SQI",
        "Sodicity-expanded SQI with ECe scored as more-is-better",
    ]

    df = df[df["SQI candidate"].isin(ec_order)].copy()
    df["candidate_order"] = df["SQI candidate"].map(
        {candidate: index for index, candidate in enumerate(ec_order)}
    )
    df = df.sort_values("candidate_order").drop(columns="candidate_order")

    rename_columns = {
        "n": "n",
        "spearman_rho": "Spearman rho",
        "pearson_r": "Pearson r",
        "linear_r2": "OLS R²",
        "rmse": "RMSE",
        "farm_fixed_r2": "Farm fixed R²",
        "farm_fixed_aic": "Farm fixed AIC",
        "farm_fixed_sqi_p": "Farm fixed SQI p",
    }

    output = df.rename(columns=rename_columns)

    preferred_columns = [
        "SQI candidate",
        "n",
        "Spearman rho",
        "Pearson r",
        "OLS R²",
        "RMSE",
        "Farm fixed R²",
        "Farm fixed AIC",
        "Farm fixed SQI p",
    ]

    keep_columns = [column for column in preferred_columns if column in output.columns]
    return output[keep_columns]


def create_main_validation_figure() -> None:
    """Create the article-ready main validation figure."""
    df = pd.read_csv(SELECTED_SQI_PATH)

    required_columns = [MAIN_SQI_COLUMN, RESPONSE_COLUMN]
    missing_columns = [column for column in required_columns if column not in df.columns]
    if missing_columns:
        raise ValueError(f"Missing columns in selected SQI dataset: {missing_columns}")

    plot_df = df[required_columns].dropna().copy()
    x = plot_df[MAIN_SQI_COLUMN].astype(float).to_numpy()
    y = plot_df[RESPONSE_COLUMN].astype(float).to_numpy()

    spearman = stats.spearmanr(x, y)
    slope, intercept, r_value, p_value, _ = stats.linregress(x, y)
    r_squared = r_value**2

    x_line = np.linspace(x.min(), x.max(), 200)
    y_line = intercept + slope * x_line

    fig, ax = plt.subplots(figsize=(7.2, 5.0))

    ax.scatter(x, y)
    ax.plot(x_line, y_line)

    ax.set_xlabel("Integrated SQI")
    ax.set_ylabel("Relative yield per plant (%)")

    equation = f"y = {intercept:.2f} + {slope:.2f} × SQI"
    annotation = (
        f"n = {len(plot_df)}\n"
        f"{equation}\n"
        f"Spearman rho = {spearman.statistic:.3f}\n"
        f"p < 0.001\n"
        f"R² = {r_squared:.3f}"
    )

    ax.text(
        0.04,
        0.96,
        annotation,
        transform=ax.transAxes,
        va="top",
        ha="left",
    )

    ax.set_title("")

    fig.tight_layout()

    png_path = FIGURE_OUTPUT_DIR / "article_integrated_sqi_validation.png"
    pdf_path = FIGURE_OUTPUT_DIR / "article_integrated_sqi_validation.pdf"

    fig.savefig(png_path, dpi=300)
    fig.savefig(pdf_path)
    plt.close(fig)

    print(f"Created: {png_path}")
    print(f"Created: {pdf_path}")


def create_article_candidate_comparison_figure(df: pd.DataFrame) -> None:
    """Create a 2 x 2 article-ready candidate comparison panel."""
    fig, axes = plt.subplots(2, 2, figsize=(12.0, 7.2))
    axes = axes.flatten()

    candidates = df["SQI candidate"].tolist()
    y_positions = range(len(candidates))

    for ax, metric in zip(axes, METRICS):
        column = metric["column"]
        label = metric["label"]

        values = pd.to_numeric(df[column], errors="coerce").tolist()

        ax.barh(y_positions, values)
        ax.set_yticks(y_positions)
        ax.set_yticklabels(candidates)
        ax.invert_yaxis()
        ax.set_xlim(*metric["xlim"])
        ax.set_xlabel(label)
        ax.set_title(label)

        for y_position, value in zip(y_positions, values):
            if pd.notna(value):
                ax.text(
                    value + 0.01,
                    y_position,
                    f"{value:.3f}",
                    va="center",
                )

    fig.suptitle("")
    fig.tight_layout()

    png_path = FIGURE_OUTPUT_DIR / "article_candidate_comparison_4_candidates.png"
    pdf_path = FIGURE_OUTPUT_DIR / "article_candidate_comparison_4_candidates.pdf"

    fig.savefig(png_path, dpi=300, bbox_inches="tight")
    fig.savefig(pdf_path, bbox_inches="tight")
    plt.close(fig)

    print(f"Created: {png_path}")
    print(f"Created: {pdf_path}")


def save_article_tables(candidate_df: pd.DataFrame, ec_df: pd.DataFrame) -> None:
    """Save article-ready CSV and markdown tables."""
    candidate_csv = TABLE_OUTPUT_DIR / "article_candidate_validation_table.csv"
    candidate_md = TABLE_OUTPUT_DIR / "article_candidate_validation_table.md"

    ec_csv = TABLE_OUTPUT_DIR / "article_ec_sensitivity_table.csv"
    ec_md = TABLE_OUTPUT_DIR / "article_ec_sensitivity_table.md"

    candidate_df.to_csv(candidate_csv, index=False)
    ec_df.to_csv(ec_csv, index=False)

    write_markdown_table(format_numeric_columns(candidate_df), candidate_md)
    write_markdown_table(format_numeric_columns(ec_df), ec_md)

    print(f"Created: {candidate_csv}")
    print(f"Created: {candidate_md}")
    print(f"Created: {ec_csv}")
    print(f"Created: {ec_md}")


def main() -> None:
    """Create article-ready SQI outputs."""
    ensure_output_dirs()

    candidate_df = prepare_article_candidate_table()
    ec_df = prepare_article_ec_sensitivity_table()

    save_article_tables(candidate_df, ec_df)
    create_main_validation_figure()
    create_article_candidate_comparison_figure(candidate_df)

    print()
    print("Article-ready SQI outputs created.")
    print("Main candidate name: Integrated SQI")
    print("No internal SQI codes are used in the article-ready tables or figures.")


if __name__ == "__main__":
    main()
